# Create the ADU - MECH GENERAL NOTES drafting view and place it on ADU-5.
from Autodesk.Revit.DB import (FilteredElementCollector as FEC, ViewDrafting, ViewFamilyType,
                               ViewFamily, ViewSheet, Viewport, TextNote, TextNoteType,
                               TextNoteOptions, HorizontalTextAlignment, BuiltInParameter as BIP,
                               XYZ as _XYZ, ElementId)
NAME = 'ADU - MECH GENERAL NOTES'
TXT = (
"MECHANICAL GENERAL NOTES:\n"
"1) BUILDING IS TWO STORY.\n"
"2) FURNISH ALL LABOR, MATERIALS, TOOLS, EQUIPMENT, FEES, PERMITS, CERTIFICATE OF INSPECTION, ETC., "
"NECESSARY OR REASONABLY REQUIRED FOR THE COMPLETE INSTALLATION OF ALL AIR CONDITIONING WORK. THE WORK "
"SHALL BE IN STRICT ACCORDANCE WITH THE ASHRAE GUIDE, AND ALL LOCAL AND STATE CODES, ORDINANCES AND REGULATIONS.\n"
"3) COORDINATE ALL MECHANICAL WORK WITH ARCHITECT AND OTHER TRADES PRIOR TO WORK.\n"
"4) ALL OUTSIDE AIR INTAKES SHALL BE MINIMUM 10 FEET FROM ANY EXHAUST OR PLUMBING VENTS - COORDINATE "
"WITH PLUMBING CONTRACTOR.\n"
"5) EXHAUST DUCTS MUST TERMINATE 10 FEET HORIZONTALLY FROM OR 3 FEET ABOVE ALL AIR INTAKES.\n"
"\nEQUIPMENT:\n"
"1) MECHANICAL CONTRACTOR TO VERIFY AND COORDINATE AVAILABLE VOLTAGE WITH ELECTRICAL CONTRACTOR PRIOR "
"TO ORDERING EQUIPMENT.\n"
"2) ALL MECHANICAL EQUIPMENT LOCATIONS TO COMPLY WITH THE 2022 CMC.\n"
"3) SET A/C UNITS TO OUTSIDE AIR QUANTITIES AS SPECIFIED ON FLOOR PLAN.\n"
"4) ALL HVAC EQUIPMENT (A/C UNITS, EXHAUST FANS, ETC.) SHALL BE U.L. LISTED.\n"
"5) ALL MOTORS SHALL BE INHERENTLY THERMALLY PROTECTED.\n"
"6) CONTRACTOR SHALL MOUNT ALL MECHANICAL EQUIPMENT LEVEL IN CONFORMANCE WITH MANUFACTURER'S INSTRUCTIONS.\n"
"7) PROVIDE ONE SET OF FARR 30-30 THROWAWAY FILTERS AND ONE SET OF FINAL FILTERS, FRAMES, MOUNTING "
"HARDWARE AND ACCESSORIES. PROVIDE ONE SET OF THROWAWAY FILTERS FOR USE DURING THE CONSTRUCTION PERIOD. "
"REMOVE THE FIRST SET OF THROWAWAY FILTERS AFTER THE CONSTRUCTION PERIOD AND INSTALL THE SECOND SET OF "
"FINAL FILTERS (PRIOR TO BALANCING THE SYSTEM).\n"
"\nDUCT WORK:\n"
"1) THE MAXIMUM LENGTH OF ANY FLEX DUCT SHALL NOT EXCEED 8 FEET.\n"
"2) ALL SUPPLY AND RETURN DUCTS SHALL HAVE A MINIMUM OF R-6 INSULATION (R-8 IN UNCONDITIONED ATTIC) PER "
"THE CALIFORNIA ENERGY CODE.\n"
"3) ALL JOINTS, LONGITUDINAL AND TRANSVERSE SEAMS AND CONNECTIONS IN DUCTWORK SHALL BE SECURELY FASTENED "
"AND SEALED WITH WELDS, GASKETS, MASTICS (ADHESIVES), MASTIC-PLUS-EMBEDDED-FABRIC SYSTEMS OR TAPES. TAPES "
"AND MASTICS USED TO SEAL DUCTWORK SHALL BE LISTED AND LABELED IN ACCORDANCE WITH UL 181A AND SHALL BE "
"MARKED 181A-P FOR PRESSURE SENSITIVE TAPE. TAPES AND MASTICS USED TO SEAL FLEXIBLE AIR DUCT AND FLEXIBLE "
"CONNECTORS SHALL COMPLY WITH UL 181B AND SHALL BE MARKED 181B-FX FOR PRESSURE SENSITIVE TAPE OR 181M FOR "
"MASTIC. DUCT CONNECTIONS TO FLANGES OF AIR DISTRIBUTION SYSTEM EQUIPMENT SHALL BE SEALED AND MECHANICALLY "
"FASTENED. UNLISTED DUCT TAPE IS NOT PERMITTED AS SEALANT ON ANY METAL DUCTS.\n"
"4) ALL DUCTS SHALL BE SUBSTANTIALLY SUPPORTED WITH HANGERS TO THE STRUCTURE. SHEET METAL SHALL BE IN "
"ACCORDANCE WITH THE FOLLOWING SCHEDULE: UP TO 12\" WIDTH - 26 GAUGE STEEL; 13\" TO 30\" WIDTH - 24 GAUGE STEEL.\n"
"5) ALL \"FACTORY MADE\" DUCT MUST BE CLASS '0' OR CLASS '1'.\n"
"6) ALTERNATE FOR SHEET METAL DUCTWORK, FOR AIR CONDITIONING SUPPLY AND RETURN: 1-1/2\" THICK FIBERGLASS "
"DUCTBOARD, WITH FOIL-SCRIM-KRAFT FIRE RESISTANT OUTER JACKET. MATERIAL SHALL COMPLY WITH UL-181, NFPA 90A "
"AND 90B. CLOSURES SHALL BE MADE WITH THERMAL-ACTIVATED TAPE, OR CLOTH TAPE SET IN BRUSH-APPLIED ADHESIVE. "
"DO NOT UTILIZE PRESSURE SENSITIVE TAPE.\n"
"\nOUTLETS:\n"
"1) THE MECHANICAL CONTRACTOR SHALL COORDINATE EXACT DIFFUSER AND GRILLE LOCATIONS WITH ELECTRICAL "
"CONTRACTOR AND ALL OTHER TRADES, AND ALSO COORDINATE SPACE AVAILABILITY FOR DUCTWORK ABOVE RECESSED "
"LIGHTING TO AVOID RELOCATING DUCTWORK AT THE MECHANICAL CONTRACTOR'S EXPENSE.\n"
"2) ALL AIR DISTRIBUTION DEVICES IN LAY-IN CEILINGS SHALL BE SUPPORTED IN COMPLIANCE WITH NFPA 90A AND THE "
"2022 CBC.\n"
"\nCONTROLS:\n"
"1) THERMOSTATS SHALL BE 7-DAY PROGRAMMABLE, SET WITH FAN ON CONTINUOUSLY.\n"
"\nFIRE:\n"
"1) APPROVED SMOKE DETECTOR DEVICES SHALL BE INSTALLED WITH ALL AIR MOVING SYSTEMS (EITHER INDEPENDENT OR "
"COMBINED IN A COMMON PLENUM OR SERVING A COMMON ROOM) OVER 2000 CFM, LOCATED IN THE SUPPLY AIR DUCTWORK. "
"DEVICES SHALL AUTOMATICALLY SHUT DOWN THE UNIT WHEN PARTICLES OF COMBUSTION ARE DETECTED WITHIN THE AIR "
"STREAM, PER THE 2022 CMC.\n"
"2) ALL SMOKE DETECTORS SHALL BE TESTED BY AN AABC OR NEBB CERTIFIED AIR BALANCE TECHNICIAN PER CITY OF "
"SAN DIEGO REQUIREMENTS FOR SPECIAL INSPECTIONS IN COMPLIANCE WITH THE 2022 C.M.C. THE MECHANICAL "
"CONTRACTOR SHALL INCLUDE ALL FEES FOR THESE TESTS AND INSPECTIONS IN HIS BID.\n"
"3) IF THERE IS A FIRE ALARM SYSTEM, ALL SMOKE DETECTORS SHALL BE MONITORED BY THAT SYSTEM.\n"
"\nPIPING:\n"
"1) HANGERS AND SUPPORTS: CLEVIS HANGERS, ADJUSTABLE HEIGHT, MAXIMUM 10' O.C., 3/8\" ROD UP TO 5\" PIPES, "
"5/8\" ROD FOR 6\" AND LARGER. WHERE EXTRA HANGER SUPPORTS ARE REQUIRED THEY SHALL BE PROVIDED BY THE "
"CONTRACTOR. TRAPEZE HANGERS WITH ROLLERS MAY BE USED FOR MULTIPLE LINES OR WHERE SPACE IS LIMITED.\n"
"\nINSULATION:\n"
"1) ALL INSULATION, MATERIAL, COVERINGS, ADHESIVES, VAPOR-BARRIERS AND TAPES SHALL CONFORM TO NFPA 90A, "
"FLAME SPREAD CLASSIFICATION NOT TO EXCEED 25 AND SMOKE DEVELOPMENT NOT TO EXCEED 50.\n"
"2) PROVIDE 1/2\" LINER IN SUPPLY AND RETURN DUCTWORK OF AIR CONDITIONING SYSTEMS.\n"
"3) INSULATE ALL SHEET METAL DUCTWORK FOR AIR CONDITIONING SYSTEM WITH 1-1/2\", 3/4 LB. DENSITY EXTERIOR "
"INSULATION, WITH FSK JACKET AND VAPOR BARRIER.")
L = []
exists = [v for v in FEC(doc).OfClass(ViewDrafting) if not v.IsTemplate and v.Name == NAME]
t = Transaction(doc, 'OneTake: mech general notes'); _prep(t); t.Start()
if exists:
    dv = exists[0]; L.append('view exists %s' % dv.Id)
else:
    vft = None
    for ft in FEC(doc).OfClass(ViewFamilyType):
        if ft.ViewFamily == ViewFamily.Drafting: vft = ft; break
    dv = ViewDrafting.Create(doc, vft.Id)
    dv.Name = NAME
    dv.Scale = 1
    tt = None
    for t2 in FEC(doc).OfClass(TextNoteType):
        if (t2.get_Parameter(BIP.SYMBOL_NAME_PARAM).AsString() or '') == '3/32" Arial':
            tt = t2; break
    o = TextNoteOptions(tt.Id)
    o.HorizontalAlignment = HorizontalTextAlignment.Left
    TextNote.Create(doc, dv.Id, _XYZ(0, 0, 0), 0.62, TXT, o)
    L.append('created view %s with wrapped note' % dv.Id)
doc.Regenerate()
sh = None
for s in FEC(doc).OfClass(ViewSheet):
    if s.SheetNumber == 'ADU-5': sh = s; break
have = any(doc.GetElement(vp.ViewId).Id == dv.Id for vp in FEC(doc, sh.Id).OfClass(Viewport))
if not have and Viewport.CanAddViewToSheet(doc, sh.Id, dv.Id):
    vp = Viewport.Create(doc, sh.Id, dv.Id, _XYZ(2.42, 0.50, 0))
    vp.LabelOffset = _XYZ(0, 0, 0)
    doc.Regenerate()
    ol = vp.GetBoxOutline()
    L.append('placed on ADU-5: box %.2f x %.2f' % (
        ol.MaximumPoint.X - ol.MinimumPoint.X, ol.MaximumPoint.Y - ol.MinimumPoint.Y))
doc.Regenerate(); t.Commit()
result = '\n'.join(L)
